class MarsConfig:
    SEED = 1
    ROVER_MAX_ENERGY = 100
    ROVER_MIN_ENERGY = 0
    ROVER_MOVE_ENERGY = 15
    ROCK_MAX_ENERGY = 10
    ROCK_MIN_ENERGY = 1
    ROCK_SPAWN_RATE = 100
    INITIAL_ROVERS = 4
