class OceanConfig:
    SEED = 1
    SHARK_BREEDING_ENERGY = 1
    SHARK_BREEDING_PROBABILITY = 5
    SHARK_MAX_AGE = 20
    SHARK_MAX_ENERGY = 20
    SHARK_MOVE_ENERGY = 1
    PLANKTON_BREEDING_ENERGY = 5
    PLANKTON_BREEDING_PROBABILITY = 60
